#!/bin/sh

stash_name=$1
git_command=SAND

## if more than one by stash_name, we get the most recent one
get_stash_real_name_by_desc() {
    name=$1
    git stash list --pretty='%gd %s' | grep -E "^stash[^:]*: ($name)$" | head -1 | awk '{print $1}'
}

check_git_installed() {
    # Check if Git is installed
    git --version 2>/dev/null 1>/dev/null
    if [ ! $? -eq 0 ]; then
        echo "[$git_command] Git is not installed. Please install Git and try again."
        exit 1
    fi
}

check_git_installed $git_command


if [ -z "$stash_name" ]
then
    echo "[$git_command] Missing stash name"
    exit 1;
fi

echo "[$git_command] Retrieving stash \"$stash_name\" ..."
stash_real_name=$(get_stash_real_name_by_desc $stash_name)

if [ -z "$stash_real_name" ]
then
    echo "[$git_command] Could not find a stash by \"$stash_name\""
    exit 1;
fi

echo "[$git_command] Applying \"$stash_real_name\":\"$stash_name\" ..."
git stash apply $stash_real_name

if [ ! $? -eq 0 ]
then
    echo "[$git_command] Could not retrieve \"$stash_real_name\""
    exit 1;
fi

echo "[$git_command] Dropping \"$stash_real_name\":\"$stash_name\" from the stash list ..."
git stash drop $stash_real_name

if [ ! $? -eq 0 ]
then
    echo "[$git_command] Could not drop \"$stash_real_name\""
    exit 1;
fi

exit 0;
